services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    env_file:
      - .env
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - app

  app:
    build:
      dockerfile: Dockerfile
      target: runner
    env_file:
      - .env
    expose:
      - 3000
    stop_grace_period: 1s
